services:
  - type: web
    name: link-please
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: MOCK_API_BASE_URL
        value: https://pseudogram-api.onrender.com
